#!/bin/bash
# =============================================================================
# @author: https://github.com/abnvle
# Cloudflare Real IP Script for Nginx
# Configures Nginx to restore original client IPs from Cloudflare proxy
#
# Recommended: add to cron to keep Cloudflare IPs up to date
#   sudo crontab -e
#   0 3 * * 0 /path/to/cf-real-ip.sh >> /var/log/cf-real-ip.log 2>&1
# =============================================================================

set -euo pipefail

# ======================== CONFIGURATION ========================
NGINX_CF_CONF="/etc/nginx/conf.d/cloudflare-real-ip.conf"
# ===============================================================

# Check root privileges
if [[ $EUID -ne 0 ]]; then
    echo "[ERROR] This script must be run as root: sudo $0"
    exit 1
fi

echo "[INFO] Configuring Nginx to restore real client IPs..."
echo "       Output: $NGINX_CF_CONF"
echo ""

# Fetch current Cloudflare IP ranges
echo "[INFO] Fetching Cloudflare IP ranges..."
CF_IPV4=$(curl -sf https://www.cloudflare.com/ips-v4) || {
    echo "[ERROR] Failed to fetch Cloudflare IPv4 ranges"
    exit 1
}
CF_IPV6=$(curl -sf https://www.cloudflare.com/ips-v6) || {
    echo "[ERROR] Failed to fetch Cloudflare IPv6 ranges"
    exit 1
}

echo "       IPv4: $(echo "$CF_IPV4" | wc -l) ranges"
echo "       IPv6: $(echo "$CF_IPV6" | wc -l) ranges"
echo ""

# Generate Nginx config
echo "[INFO] Generating Nginx config..."

{
    echo "# Cloudflare Real IP Configuration"
    echo "# Auto-generated by cf-real-ip.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
    echo "# Do not edit manually - changes will be overwritten"
    echo ""
    echo "# IPv4"
    while IFS= read -r ip; do
        [[ -z "$ip" ]] && continue
        echo "set_real_ip_from $ip;"
    done <<< "$CF_IPV4"
    echo ""
    echo "# IPv6"
    while IFS= read -r ip; do
        [[ -z "$ip" ]] && continue
        echo "set_real_ip_from $ip;"
    done <<< "$CF_IPV6"
    echo ""
    echo "real_ip_header CF-Connecting-IP;"
} > "$NGINX_CF_CONF"

echo "[OK] Config written to $NGINX_CF_CONF"
echo ""

# Test and reload Nginx
echo "[INFO] Testing Nginx configuration..."
if nginx -t 2>&1; then
    echo ""
    echo "[INFO] Reloading Nginx..."
    nginx -s reload
    echo "[OK] Nginx reloaded successfully."
else
    echo ""
    echo "[ERROR] Nginx config test failed. Check your configuration."
    echo "        The file was written but Nginx was NOT reloaded."
    exit 1
fi